Лабораторная работа номер 2 "Нормы, разложение матрицы"
Вариант 6. 
Выполнил: Чугунов Владислав 6311-100503D
Часть 1.

1. Создать квадратную матрицу из случайных целых чисел из
[-7,-2] размера 9. Найти и вычислить минор 4 порядка, расположенный на пересечении 1, 2, 3, 4 строк и 2, 3, 8, 9 столбцов. Использовать срезы матрицы.


In [3]:
import numpy as np

In [4]:
#Создаем матрицу из рандомных числел в пределах [-7, -2] размером 9x9
matrix = np.random.randint(-7, -1, (9, 9))
print(matrix)

[[-2 -7 -6 -6 -4 -7 -3 -4 -3]
 [-4 -6 -5 -3 -3 -7 -5 -7 -7]
 [-2 -4 -3 -7 -3 -3 -3 -7 -5]
 [-2 -4 -5 -6 -2 -7 -5 -3 -5]
 [-4 -7 -5 -6 -3 -2 -6 -3 -2]
 [-2 -5 -5 -7 -6 -3 -7 -4 -2]
 [-2 -6 -3 -5 -6 -4 -5 -3 -7]
 [-7 -7 -4 -6 -5 -6 -3 -3 -7]
 [-7 -3 -3 -5 -3 -2 -6 -5 -5]]


In [5]:
#Находим минор 4 порядка
matrix = matrix[:4]
matrix = matrix[:4, [0,1,7,8]]
print(matrix[1:, 1:])

minor = np.linalg.det(matrix[1:, 1:])
print(minor)

[[-6 -7 -7]
 [-4 -7 -5]
 [-4 -3 -5]]
-8.000000000000009


2. Создать две матрицы из случайных вещественных чисел
подходящего размера. Найти их произведение тремя способами:
используя векторный алгоритм умножения матриц; используя
матричный алгоритм, записав матрицу С по столбцам; проверив с
помощью функции np.dot. 

In [15]:
matrix_first = np.random.randint(-5, 5, (4, 4))
matrix_first = matrix_first /3.28
matrix_second = np.random.randint(-10, 10, (4, 4))
matrix_second = matrix_second /3.28
print(matrix_first,"\n", matrix_second)

[[ 0.         -0.91463415 -0.30487805 -0.30487805]
 [-0.30487805 -1.52439024  0.30487805 -0.30487805]
 [ 0.6097561   0.         -1.52439024  1.2195122 ]
 [ 0.6097561   0.6097561   0.30487805  0.30487805]] 
 [[-1.2195122  -0.30487805 -1.52439024  0.        ]
 [ 1.2195122  -0.6097561   0.6097561   0.        ]
 [-2.43902439 -1.82926829  2.43902439  1.82926829]
 [ 0.91463415 -2.74390244 -0.6097561  -1.52439024]]


In [20]:
#Проверка
print(np.dot(matrix_first, matrix_second))

[[-6.50654372e-01  1.95196312e+00 -1.11540750e+00 -9.29506246e-02]
 [-2.50966686e+00  1.30130874e+00  4.64753123e-01  1.02245687e+00]
 [ 4.08982748e+00 -7.43604997e-01 -5.39113623e+00 -4.64753123e+00]
 [-4.64753123e-01 -1.95196312e+00  1.22514201e-17  9.29506246e-02]]


In [17]:
#Векторный способ умножения матриц
result = np.zeros((4,4), dtype=int)
for i in range(0, 4):
    for j in range(0, 4):
        result[i,j] = np.dot(matrix_first[i,:], matrix_second[:,j])
print(result)

[[ 0  1 -1  0]
 [-2  1  0  1]
 [ 4  0 -5 -4]
 [ 0 -1  0  0]]


In [18]:
#Матричный способ умножения матриц
result_ = np.zeros((4,4), dtype=int)
for i in range(0,4):
    result_[i,:] = np.dot(matrix_first[i,:], matrix_second)
print(result_)

[[ 0  1 -1  0]
 [-2  1  0  1]
 [ 4  0 -5 -4]
 [ 0 -1  0  0]]


3. Создать вектор-строку 1x8 из случайных целых чисел. Вычислить норму ‖x‖3
 самостоятельно написанной функцией и
проверить результат с помощью linalg.norm().

In [22]:
#Создадим вектор и вычислим норму
line_x8 = np.random.randint(-10, 10, (8))
norma_3 = 0
for i in range(line_x8.size):
    norma_3 = norma_3 + pow(abs(line_x8[i]), 3)
print("Собственный алгоритм",pow(norma_3, 1/3))
print("Используя алгоритм", np.linalg.norm(line_x8, ord=3))

Собственный алгоритм 12.52103126170399
Используя алгоритм 12.52103126170399


4. Создать матрицу из случайных целых чисел. Найти спектральную норму матрицы с помощью самостоятельно написанного
алгоритма (можно использовать функцию для нахождения собственных значений), проверить результат с помощью linalg.norm()

In [23]:
line_8x8 = np.random.randint(0, 10, (8,8))
print("Используя алгоритм", np.linalg.norm(line_8x8, 2))

Используя алгоритм 37.5757832218482


In [24]:
#Создадим вектор и вычислим норму
eigenvalues, _ = np.linalg.eig(np.dot(line_8x8.T, line_8x8))
spectral_norm = np.sqrt(np.max(eigenvalues))

print("Собственный алгоритм:", spectral_norm)
line_x8 = np.random.randint(-10, 10, (8))

(r, c) = np.shape(line_x8)
Q = np.identity(r)
R = np.empty_like(line_x8)
for cnt in range(r - 1):
    x= R[cnt:, cnt]
    e = np.zeros_like(x)
    e[0] = np.linalg.norm(x)
    u = x - e
    v = u / np.linalg.norm(u)
    Q_cnt = np.identity(r)
    Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)
    R = np.dot(Q_cnt, R)
    Q = np.dot(Q, Q_cnt) # Q = H (N-1) * … * H (2) *H (1) H
np.set_printoptions(precision=4, suppress=True)
print(Q)
print(R)

Собственный алгоритм: 37.5757832218482


5. Для вектора, созданного в третьем пункте, найти отражение Хаусхолдера, которое обнуляет его координаты с 4 по 8.
Например, вектор (1,2,3,4,5,6,7,8) переводит в вектор
(1,2,c,0,0,0,0,0)

In [38]:
vector = np.random.randint(-10, 11, size = 8)
array = np.array(vector, dtype=float)
print("Исходный вектор: ",array)
y = np.array((array[2:]), dtype = float)
print("y: ",y)
if array[2] < 0:
    beta = np.linalg.norm(y, 2)
else:
    beta = -1* np.linalg.norm(y, 2)
print("B:\n",beta)

u = np.array((y[0] - beta, y[1], y[2], y[3], y[4], y[5]))
print("u:\n", u)
v = u / np.linalg.norm(u, 2)
print("v:\n", v)

E = np.eye(6,6)
v_transpose = v.reshape(-1, 1)

H_s = E - 2 * v * v_transpose
print("H':\n",H_s)

H = np.eye(8,8)
row_start, row_end = 2, 8
col_start, col_end = 2, 8
H[row_start:row_end, col_start:col_end] = H_s
print("H:\n",H)

array_transpose = array.reshape(-1, 1)

result = np.dot(H, array)
print("Исходный вектор: ",array)
print("РЕЗУЛЬТАТ:\n",result)

Исходный вектор:  [ -1.  -3.   4.   5. -10.   9.  -9.   5.]
y:  [  4.   5. -10.   9.  -9.   5.]
B:
 -18.110770276274835
u:
 [ 22.11   5.   -10.     9.    -9.     5.  ]
v:
 [ 0.78  0.18 -0.35  0.32 -0.32  0.18]
H':
 [[-0.22 -0.28  0.55 -0.5   0.5  -0.28]
 [-0.28  0.94  0.12 -0.11  0.11 -0.06]
 [ 0.55  0.12  0.75  0.22 -0.22  0.12]
 [-0.5  -0.11  0.22  0.8   0.2  -0.11]
 [ 0.5   0.11 -0.22  0.2   0.8   0.11]
 [-0.28 -0.06  0.12 -0.11  0.11  0.94]]
H:
 [[ 1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.   -0.22 -0.28  0.55 -0.5   0.5  -0.28]
 [ 0.    0.   -0.28  0.94  0.12 -0.11  0.11 -0.06]
 [ 0.    0.    0.55  0.12  0.75  0.22 -0.22  0.12]
 [ 0.    0.   -0.5  -0.11  0.22  0.8   0.2  -0.11]
 [ 0.    0.    0.5   0.11 -0.22  0.2   0.8   0.11]
 [ 0.    0.   -0.28 -0.06  0.12 -0.11  0.11  0.94]]
Исходный вектор:  [ -1.  -3.   4.   5. -10.   9.  -9.   5.]
РЕЗУЛЬТАТ:
 [ -1.    -3.   -18.11   0.    -0.     0.    -0.     0.  ]


6. Для матрицы, созданной в 4 пункте, найти LU разложение
самостоятельно написанной функцией и проверить результат с
помощью перемножения матриц.

In [39]:
line_8x8 = np.random.randint(0, 10, (8,8))
def LU(line_8x8):
    size = line_8x8[0].size
    print(size)
    U = np.zeros((size,size), float)
    L = np.identity(size, float)
    for i in range(size):
        L[i, i] = 1
        for k in range(i, size):
            sum_uk = 0
            sum_lk = 0
            for j in range(i):
                sum_uk += L[i, j] * U[j, k]
                sum_lk += L[k, j] * U[j, i]
            U[i, k] = line_8x8[i, k] - sum_uk
            L[k, i] = (line_8x8[k, i] - sum_lk) / U[i, i]
    return L, U
L, U = LU(line_8x8)
np.set_printoptions(precision=2, suppress=True)
print("U = ",U,"\nL = ",L)



8
U =  [[  9.     5.     9.     3.     0.     5.     8.     6.  ]
 [  0.     4.    -4.    -2.     5.     3.     0.     0.  ]
 [  0.     0.    -2.44   3.11   4.56  -2.11   0.89  -2.33]
 [  0.     0.     0.     9.36   5.82  -6.82   1.82  -7.27]
 [  0.     0.     0.     0.     2.54   5.74   1.67   7.82]
 [  0.     0.     0.     0.     0.    -2.81  -8.39   0.78]
 [  0.     0.     0.     0.     0.     0.    48.31 -15.32]
 [  0.     0.     0.     0.     0.     0.     0.    -7.31]] 
L =  [[ 1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 1.    1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.89  0.89  1.    0.    0.    0.    0.    0.  ]
 [ 0.56  1.56 -2.55  1.    0.    0.    0.    0.  ]
 [ 0.22  1.72 -4.05  2.28  1.    0.    0.    0.  ]
 [ 0.89  1.14 -0.23  0.35  0.5   1.    0.    0.  ]
 [ 0.33  0.83 -2.59  1.15  2.35  5.44  1.    0.  ]
 [ 0.    0.25 -2.05  1.48  2.93  2.42  0.42  1.  ]]


In [40]:
print(line_8x8)
print("Проверка \n",np.dot(L, U))

[[9 5 9 3 0 5 8 6]
 [9 9 5 1 5 8 8 6]
 [8 8 2 4 9 5 8 3]
 [5 9 5 0 2 6 4 2]
 [2 8 5 6 6 5 4 2]
 [8 9 4 3 8 6 0 8]
 [3 5 6 2 5 0 9 7]
 [0 1 4 7 8 5 6 5]]
Проверка 
 [[9. 5. 9. 3. 0. 5. 8. 6.]
 [9. 9. 5. 1. 5. 8. 8. 6.]
 [8. 8. 2. 4. 9. 5. 8. 3.]
 [5. 9. 5. 0. 2. 6. 4. 2.]
 [2. 8. 5. 6. 6. 5. 4. 2.]
 [8. 9. 4. 3. 8. 6. 0. 8.]
 [3. 5. 6. 2. 5. 0. 9. 7.]
 [0. 1. 4. 7. 8. 5. 6. 5.]]


7. Для матрицы, созданной в 4 пункте, найти QR разложение
всеми рассмотренными методами, проверить результат с помощью
перемножения матриц и с помощью функции np.linalg.qr.

In [50]:
#алгоритм грамма шмидта
line_8x8 = line_8x8.astype(float)
n = line_8x8.shape[1]
Q = np.zeros_like(line_8x8)
R = np.zeros((n, n))

for j in range(n):
    v = line_8x8[:, j]
    for i in range(j):
        R[i, j] = np.dot(Q[:, i], line_8x8[:, j])
        v = v - (R[i, j] * Q[:, i])
    R[j, j] = np.linalg.norm(v)
    Q[:, j] = v / R[j, j]



print("\nМатрица Q (Грама-Шмидта):\n", Q)
print("\nМатрица R (Грама-Шмидта):\n", R)




Матрица Q (Грама-Шмидта):
 [[ 0.4969 -0.4979  0.5562 -0.0509 -0.4111 -0.1142 -0.0458 -0.0951]
 [ 0.4969 -0.032  -0.1445 -0.1756  0.1625  0.4689  0.3012  0.6028]
 [ 0.4417 -0.0284 -0.4415  0.455   0.0272 -0.3112  0.4449 -0.3265]
 [ 0.2761  0.4482  0.0161 -0.4891 -0.0845  0.3271  0.061  -0.6046]
 [ 0.1104  0.6918  0.1836  0.2419 -0.5128 -0.1935  0.0156  0.3411]
 [ 0.4417  0.0881 -0.2324  0.1305  0.1973 -0.0463 -0.8274  0.0191]
 [ 0.1656  0.2223  0.4128 -0.2278  0.6303 -0.5269  0.1418  0.0769]
 [ 0.      0.1165  0.4653  0.6268  0.3124  0.496   0.0231 -0.1813]]

Матрица R (Грама-Шмидта):
 [[18.1108 18.6629 12.534   6.0737 12.037  13.5279 14.5217 12.7548]
 [ 0.      8.5846  3.1544  4.0359  7.3799  4.3718  2.7936  1.8588]
 [ 0.      0.      7.807   4.2451  0.3649  1.3644  7.0671  4.9017]
 [ 0.      0.      0.      7.2664  8.609   2.8073  2.5493  2.0946]
 [ 0.      0.      0.      0.      5.0397 -0.9456  3.385   4.9468]
 [ 0.      0.      0.      0.      0.      4.8215 -0.8833 -0.1167]
 [ 0.

In [55]:
print("Начальная матрица",line_8x8)
print("Q * R = ",np.dot(Q, R))

Начальная матрица [[9. 5. 9. 3. 0. 5. 8. 6.]
 [9. 9. 5. 1. 5. 8. 8. 6.]
 [8. 8. 2. 4. 9. 5. 8. 3.]
 [5. 9. 5. 0. 2. 6. 4. 2.]
 [2. 8. 5. 6. 6. 5. 4. 2.]
 [8. 9. 4. 3. 8. 6. 0. 8.]
 [3. 5. 6. 2. 5. 0. 9. 7.]
 [0. 1. 4. 7. 8. 5. 6. 5.]]
Q * R =  [[ 9.  5.  9.  3. -0.  5.  8.  6.]
 [ 9.  9.  5.  1.  5.  8.  8.  6.]
 [ 8.  8.  2.  4.  9.  5.  8.  3.]
 [ 5.  9.  5. -0.  2.  6.  4.  2.]
 [ 2.  8.  5.  6.  6.  5.  4.  2.]
 [ 8.  9.  4.  3.  8.  6.  0.  8.]
 [ 3.  5.  6.  2.  5.  0.  9.  7.]
 [-0.  1.  4.  7.  8.  5.  6.  5.]]


In [42]:
np.set_printoptions(precision=4, suppress=True)
print("R",np.linalg.qr(line_8x8)[0], "\nR", np.linalg.qr(line_8x8)[1])

R [[-0.4969  0.4979  0.5562 -0.0509 -0.4111 -0.1142  0.0458  0.0951]
 [-0.4969  0.032  -0.1445 -0.1756  0.1625  0.4689 -0.3012 -0.6028]
 [-0.4417  0.0284 -0.4415  0.455   0.0272 -0.3112 -0.4449  0.3265]
 [-0.2761 -0.4482  0.0161 -0.4891 -0.0845  0.3271 -0.061   0.6046]
 [-0.1104 -0.6918  0.1836  0.2419 -0.5128 -0.1935 -0.0156 -0.3411]
 [-0.4417 -0.0881 -0.2324  0.1305  0.1973 -0.0463  0.8274 -0.0191]
 [-0.1656 -0.2223  0.4128 -0.2278  0.6303 -0.5269 -0.1418 -0.0769]
 [-0.     -0.1165  0.4653  0.6268  0.3124  0.496  -0.0231  0.1813]] 
R [[-18.1108 -18.6629 -12.534   -6.0737 -12.037  -13.5279 -14.5217 -12.7548]
 [  0.      -8.5846  -3.1544  -4.0359  -7.3799  -4.3718  -2.7936  -1.8588]
 [  0.       0.       7.807    4.2451   0.3649   1.3644   7.0671   4.9017]
 [  0.       0.       0.       7.2664   8.609    2.8073   2.5493   2.0946]
 [  0.       0.       0.       0.       5.0397  -0.9456   3.385    4.9468]
 [  0.       0.       0.       0.       0.       4.8215  -0.8833  -0.1167]
 [  0.  

In [51]:
print("Начальная матрица",line_8x8)
print("Q * R = ",np.dot(Q, R))

Начальная матрица [[9. 5. 9. 3. 0. 5. 8. 6.]
 [9. 9. 5. 1. 5. 8. 8. 6.]
 [8. 8. 2. 4. 9. 5. 8. 3.]
 [5. 9. 5. 0. 2. 6. 4. 2.]
 [2. 8. 5. 6. 6. 5. 4. 2.]
 [8. 9. 4. 3. 8. 6. 0. 8.]
 [3. 5. 6. 2. 5. 0. 9. 7.]
 [0. 1. 4. 7. 8. 5. 6. 5.]]
Q * R =  [[ 9.  5.  9.  3. -0.  5.  8.  6.]
 [ 9.  9.  5.  1.  5.  8.  8.  6.]
 [ 8.  8.  2.  4.  9.  5.  8.  3.]
 [ 5.  9.  5. -0.  2.  6.  4.  2.]
 [ 2.  8.  5.  6.  6.  5.  4.  2.]
 [ 8.  9.  4.  3.  8.  6.  0.  8.]
 [ 3.  5.  6.  2.  5.  0.  9.  7.]
 [ 0.  1.  4.  7.  8.  5.  6.  5.]]


#метод Хаусхолдера

In [52]:
(r, c) = np.shape(line_8x8)
Q = np.identity(r)
R = np.copy(line_8x8)
for cnt in range(r - 1):
    x= R[cnt:, cnt]
    e = np.zeros_like(x)
    e[0] = np.linalg.norm(x)
    u = x - e
    v = u / np.linalg.norm(u)
    Q_cnt = np.identity(r)
    Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)
    R = np.dot(Q_cnt, R)
    Q = np.dot(Q, Q_cnt) # Q = H (N-1) * … * H (2) *H (1) H
np.set_printoptions(precision=4, suppress=True)
print(Q)
print(R)

[[ 0.4969 -0.4979  0.5562 -0.0509 -0.4111 -0.1142 -0.0458 -0.0951]
 [ 0.4969 -0.032  -0.1445 -0.1756  0.1625  0.4689  0.3012  0.6028]
 [ 0.4417 -0.0284 -0.4415  0.455   0.0272 -0.3112  0.4449 -0.3265]
 [ 0.2761  0.4482  0.0161 -0.4891 -0.0845  0.3271  0.061  -0.6046]
 [ 0.1104  0.6918  0.1836  0.2419 -0.5128 -0.1935  0.0156  0.3411]
 [ 0.4417  0.0881 -0.2324  0.1305  0.1973 -0.0463 -0.8274  0.0191]
 [ 0.1656  0.2223  0.4128 -0.2278  0.6303 -0.5269  0.1418  0.0769]
 [ 0.      0.1165  0.4653  0.6268  0.3124  0.496   0.0231 -0.1813]]
[[18.1108 18.6629 12.534   6.0737 12.037  13.5279 14.5217 12.7548]
 [-0.      8.5846  3.1544  4.0359  7.3799  4.3718  2.7936  1.8588]
 [ 0.     -0.      7.807   4.2451  0.3649  1.3644  7.0671  4.9017]
 [-0.      0.      0.      7.2664  8.609   2.8073  2.5493  2.0946]
 [-0.      0.      0.     -0.      5.0397 -0.9456  3.385   4.9468]
 [-0.     -0.     -0.      0.     -0.      4.8215 -0.8833 -0.1167]
 [ 0.      0.      0.      0.     -0.      0.      7.3235 -2.

In [48]:
#проверка
print("Начальная матрица",line_8x8)
print("Q * R = ",np.dot(Q, R))

Начальная матрица [[9 5 9 3 0 5 8 6]
 [9 9 5 1 5 8 8 6]
 [8 8 2 4 9 5 8 3]
 [5 9 5 0 2 6 4 2]
 [2 8 5 6 6 5 4 2]
 [8 9 4 3 8 6 0 8]
 [3 5 6 2 5 0 9 7]
 [0 1 4 7 8 5 6 5]]
Q * R =  [[ 9.  5.  9.  3.  0.  5.  8.  6.]
 [ 9.  9.  5.  1.  5.  8.  8.  6.]
 [ 8.  8.  2.  4.  9.  5.  8.  3.]
 [ 5.  9.  5. -0.  2.  6.  4.  2.]
 [ 2.  8.  5.  6.  6.  5.  4.  2.]
 [ 8.  9.  4.  3.  8.  6. -0.  8.]
 [ 3.  5.  6.  2.  5. -0.  9.  7.]
 [ 0.  1.  4.  7.  8.  5.  6.  5.]]


Метод Гвинеса

In [53]:
def gvines(line_8x8):
    (r, c) = np.shape(line_8x8)
    Q = np.identity(r)
    R = np.copy(line_8x8)
    (rows, cols) = np.tril_indices(r, -1, c)
    for (row, col) in zip(rows, cols):
        if R[row, col] != 0: # Q = 1, S = 0, я, Q без изменений
            r_ = np.hypot(R[col, col], R[row, col]) # d
            c = R[col, col]/r_
            s = -R[row, col]/r_
            G = np.identity(r)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R) # R=G(n-1,n)*…*G(2n)*…*G(23,1 n)*…*G(12)*A
            Q = np.dot(Q, G.T) # *Q-G(n-1,n).7*…*G(2 n).7*…**G(23,in).7*…*G(12).7
    return Q, R
Q, R = gvines(line_8x8)
np.set_printoptions(precision=4, suppress=True)
print(Q)
print(R)

[[ 0.4969 -0.4979  0.5562 -0.0509 -0.4111 -0.1142 -0.0458  0.0951]
 [ 0.4969 -0.032  -0.1445 -0.1756  0.1625  0.4689  0.3012 -0.6028]
 [ 0.4417 -0.0284 -0.4415  0.455   0.0272 -0.3112  0.4449  0.3265]
 [ 0.2761  0.4482  0.0161 -0.4891 -0.0845  0.3271  0.061   0.6046]
 [ 0.1104  0.6918  0.1836  0.2419 -0.5128 -0.1935  0.0156 -0.3411]
 [ 0.4417  0.0881 -0.2324  0.1305  0.1973 -0.0463 -0.8274 -0.0191]
 [ 0.1656  0.2223  0.4128 -0.2278  0.6303 -0.5269  0.1418 -0.0769]
 [ 0.      0.1165  0.4653  0.6268  0.3124  0.496   0.0231  0.1813]]
[[18.1108 18.6629 12.534   6.0737 12.037  13.5279 14.5217 12.7548]
 [ 0.      8.5846  3.1544  4.0359  7.3799  4.3718  2.7936  1.8588]
 [-0.      0.      7.807   4.2451  0.3649  1.3644  7.0671  4.9017]
 [ 0.      0.     -0.      7.2664  8.609   2.8073  2.5493  2.0946]
 [-0.      0.      0.      0.      5.0397 -0.9456  3.385   4.9468]
 [-0.     -0.      0.      0.      0.      4.8215 -0.8833 -0.1167]
 [ 0.      0.     -0.     -0.      0.      0.      7.3235 -2.

In [54]:
print("Начальная матрица",line_8x8)
print("Q * R = ",np.dot(Q, R))

Начальная матрица [[9. 5. 9. 3. 0. 5. 8. 6.]
 [9. 9. 5. 1. 5. 8. 8. 6.]
 [8. 8. 2. 4. 9. 5. 8. 3.]
 [5. 9. 5. 0. 2. 6. 4. 2.]
 [2. 8. 5. 6. 6. 5. 4. 2.]
 [8. 9. 4. 3. 8. 6. 0. 8.]
 [3. 5. 6. 2. 5. 0. 9. 7.]
 [0. 1. 4. 7. 8. 5. 6. 5.]]
Q * R =  [[ 9.  5.  9.  3. -0.  5.  8.  6.]
 [ 9.  9.  5.  1.  5.  8.  8.  6.]
 [ 8.  8.  2.  4.  9.  5.  8.  3.]
 [ 5.  9.  5. -0.  2.  6.  4.  2.]
 [ 2.  8.  5.  6.  6.  5.  4.  2.]
 [ 8.  9.  4.  3.  8.  6.  0.  8.]
 [ 3.  5.  6.  2.  5.  0.  9.  7.]
 [-0.  1.  4.  7.  8.  5.  6.  5.]]


Лабораторная работа номер 2 "Нормы, разложение матрицы"
Вариант 6. 
Выполнил: Чугунов Владислав 6311-100503D
Часть 2.

1. Создать произвольную верхнетреугольную матрицу А 5 порядка (не унитреугольную), вектор B произвольный. Решить систему AX = B

In [56]:
matrix = np.zeros((5, 5))
j = 0
for k in range(5):
    for i in range (j, 5):
        matrix[k][i] = np.random.randint(-10, 10)
    j += 1

vector = np.random.randint(-10, 10, (5))
print(vector)
print(matrix)

[  1   9 -10   1   5]
[[ 4.  4.  0.  0.  3.]
 [ 0.  2.  9.  4.  7.]
 [ 0.  0.  7. -3. -7.]
 [ 0.  0.  0. -4. -8.]
 [ 0.  0.  0.  0. -9.]]


In [57]:
x = np.zeros((5, 1))
x[4] = vector[4]
for i in range(4, -1, -1):
    x[i] = (vector[i] - np.dot(matrix[i, i+1:], x[i+1:]))/matrix[i, i]
print(x)

print(np.dot(matrix, x))


[[-11.3234]
 [ 11.9901]
 [ -1.6151]
 [  0.8611]
 [ -0.5556]]
[[  1.]
 [  9.]
 [-10.]
 [  1.]
 [  5.]]


2. Решить систему, используя LU разложение
{
    4.3 x1−12.1 x2+23.2 x3−14.1 x 4=15.5
    2.4 x1−4.4 x2+3.5 x3+5.5 x4=2.5
    5.4 x1+8.3 x2−7.4 x3−12.7 x4=8.6
    6.3 x1−7.6 x2+1.34 x3+3.7 x4=12.1
|}

In [58]:
A = np.array([[4.3, -12.1, 23.2, -14.1],
              [2.4, -4.4, 3.5, 5.5],
              [5.4, 8.3, -7.4, -12.7],
              [6.3, -7.6, 1.34, 3.7]])

B = np.array([15.5, 2.5, 8.6, 12.1])

L, U = LU(A)

U_inverse = np.linalg.inv(U)
L_inverse = np.linalg.inv(L)
Y = L_inverse.dot(B)
X_lu = U_inverse.dot(Y)
print("Решение X:")
print(X_lu)
x_ = np.array([[1.17],[-0.97], [-0.41], [-0.58]])

print(np.dot(A, X_lu))

4
Решение X:
[ 1.1738 -0.9712 -0.4062 -0.5762]
[15.5  2.5  8.6 12.1]


Решить систему из пункта 2 с помощью QR разложения
матрицы А. QR разложение найти методом Гивенса. Проверить полученное решение непосредственной подстановкой в исходную систему, а также методом np.solve


In [60]:
A = np.array([[4.3, -12.1, 23.2, -14.1],
              [2.4, -4.4, 3.5, 5.5],
              [5.4, 8.3, -7.4, -12.7],
              [6.3, -7.6, 1.34, 3.7]])

B = np.array([15.5, 2.5, 8.6, 12.1])

Q, R = gvines(A)
R_inverse = np.linalg.inv(R)
Q_inverse = np.linalg.inv(Q)
Y = Q_inverse.dot(B)#  Y = (Q^-1)*B
x = R_inverse.dot(Y)# X = (R^-1)*Y

print(x)
x_check = np.linalg.solve(A, B)
print(x_check)  

[ 1.1738 -0.9712 -0.4062 -0.5762]
[ 1.1738 -0.9712 -0.4062 -0.5762]


. Решить систему методом простых итераций с точностью до
10−3
. Проверить выполнение достаточного условия сходимости.
Если условие не выполняется, в программе выполнить эквивалентные преобразования системы, после этого привести к удобному
для итераций виду. Оформить итерации в виде таблицы (можно
пользоваться модулями PrettyTable или Pandas).

{
3.2x1 −2.5x2 +3.7x3 = 6.5
0.5x1 +0.34x2 +1.7x3 = −0.24
1.6x1 +2.3x2 −1.5x3 = 4.3
}

In [70]:
from prettytable import PrettyTable
A = np.array([[3.2, -2.5, 3.7], [0.5, 0.34, 1.7], [1.6, 2.3, -1.5]])
B = np.array([6.5, -0.24, 4.3])
n = len(B)
print("Исходная матрица: \n", A)
print(B)
#проверка сходимости
def check(matrix):
    n = len(matrix)
    for i in range(n):
        tmp_sum = 0
        for j in range(n):
            if (j != i):
                tmp_sum += abs(matrix[i, j])
        if tmp_sum > abs(matrix[i, i]):
            print("Достаточное условие сходимости не выполняется")
            return
    print("Достаточное условие сходимости выполняется")
    return

check(A)
#у исходной матрицы условие сходимости не выполняется, значит требуется преобразовать матрицу к нужному виду
#переставляем строки
A = np.array([[4.1, 5.8, -1.7], [2.7, 3.3, 1.3], [3.5, -1.7, 2.8]])
B = np.array([0.8, 2.1, 1.7])

#складываем 1-ую и 3-ю строки
A[0,0] += A[2,0]
A[0,1] += A[2,1]
A[0,2] += A[2,2]
B[0] += B[2]
# print(A)
# print(B)

#вычитаем из 2-ой , 3-ю строку
A[1,0] -= A[2,0]
A[1,1] -= A[2,1]
A[1,2] -= A[2,2]
B[1] -= B[2]
# print(A)
# print(B)

#3-ю строку умножаем на 2
A[2,0] *= 2
A[2,1] *= 2
A[2,2] *= 2
B[2] *= 2
# print(A)
# print(B)

#из 3-ей строки вычитаем 1-ую строку умноженную на 0.5
A[2,0] -= A[0,0]*0.5
A[2,1] -= A[0,1]*0.5
A[2,2] -= A[0,2]*0.5
B[2] -= B[0]*0.5
# print(A)
# print(B)

#складываем 3-ю и 2-ую строки
A[2,0] += A[1,0]
A[2,1] += A[1,1]
A[2,2] += A[1,2]
B[2] += B[1]
print(A)
print(B)

check(A)

# Инициализация начального приближения x(0)
x = np.zeros_like(B)

# Заданная точность
tolerance = 1e-3

# Максимальное количество итераций (чтобы избежать бесконечного цикла)
max_iterations = 1000

# Создадим таблицу для вывода итераций
table = PrettyTable()
table.field_names = ["k", "x_1", "x_2", "x_3", "||x(k+1) - x(k)||"]

D = np.diag(np.diag(A))
F = A - D

for k in range(max_iterations):
    # Рассчитываем x(k+1)
    x_new = np.linalg.inv(D).dot(B - F.dot(x))

    # Вычисляем норму разницы между x(k+1) и x(k)
    norm = np.linalg.norm(x_new - x)

    # Добавляем текущую итерацию в таблицу
    table.add_row([k, x[0],x[1],x[2], norm])

    # Обновляем x для следующей итерации
    x = x_new

    # Проверяем условие завершения итераций
    if norm < tolerance:
        break

# Выводим результаты итераций
print(table)

# Выводим итоговое решение
print("Итоговое решение (x): ", x)

print("linalg.solve(): ", np.linalg.solve(A, B))

Исходная матрица: 
 [[ 3.2  -2.5   3.7 ]
 [ 0.5   0.34  1.7 ]
 [ 1.6   2.3  -1.5 ]]
[ 6.5  -0.24  4.3 ]
Достаточное условие сходимости не выполняется
[[ 7.6   4.1   1.1 ]
 [-0.8   5.   -1.5 ]
 [ 2.4  -0.45  3.55]]
[2.5  0.4  2.55]
Достаточное условие сходимости выполняется
+---+---------------------+---------------------+--------------------+-----------------------+
| k |         x_1         |         x_2         |        x_3         |   ||x(k+1) - x(k)||   |
+---+---------------------+---------------------+--------------------+-----------------------+
| 0 |         0.0         |         0.0         |        0.0         |   0.7940877942333017  |
| 1 |  0.3289473684210526 | 0.08000000000000003 | 0.7183098591549295 |   0.3722695109855704  |
| 2 | 0.18182357301704966 | 0.34812453669384724 | 0.5060637509266123 |  0.19594577860275394  |
| 3 | 0.06789727283367802 |  0.2609108969607116 | 0.6395153426116371 |  0.07480751582563594  |
| 4 | 0.09563137441951074 | 0.28271816643687964 | 0.705480689

3.2 x1−2.5 x2+3.7 x3=6.5
0.5 x1+0.34 x2+1.7 x3=−0.24
1.6 x1+2.3 x2−1.5 x3=4.3
3.6 x1+1.8 x2−4.7 x3=3.8

In [71]:

matrix_A_4 = np.array([[3.2, -2.5, 3.7], [0.5, 0.34, 1.7], [1.6, 2.3, -1.5], [3.6, 1.8, -4.7]], dtype=float)
vector_B_4 = np.array([[6.5], [-0.24], [4.3], [3.8]])

matrix_A_4_transp = matrix_A_4.transpose()
tmp_1 = np.dot(matrix_A_4_transp, matrix_A_4)
tmp_2 = np.linalg.inv(tmp_1)
tmp_3 = np.dot(np.dot(tmp_2, matrix_A_4_transp), vector_B_4)

print("\nПсевдорешение:\n", tmp_3)


Псевдорешение:
 [[1.6649]
 [0.3819]
 [0.4455]]
